info:
  version: 1.0.2
  description: NRF initial local configuration

configuration:
  MongoDBName: free5gc
  MongoDBUrl: mongodb://172.22.0.2:27017
  sbi:
    scheme: http
    registerIPv4: 172.22.0.12
    bindingIPv4: 0.0.0.0
    port: 8000
    oauth: false
  DefaultPlmnId:
    mcc: "001"
    mnc: "01"
  serviceNameList:
    - nnrf-nfm
    - nnrf-disc

logger:
  enable: true
  level: info
  reportCaller: false
