info:
  version: 1.0.2
  description: NSSF initial local configuration

configuration:
  nssfName: NSSF
  sbi:
    scheme: http
    registerIPv4: 172.22.0.28
    bindingIPv4: 0.0.0.0
    port: 8000
  serviceNameList:
    - nnssf-nsselection
    - nnssf-nssaiavailability
  nrfUri: http://172.22.0.12:8000
  supportedPlmnList:
    - mcc: "001"
      mnc: "01"
  supportedNssaiInPlmnList:
    - plmnId:
        mcc: "001"
        mnc: "01"
      supportedSnssaiList:
        - sst: 1
          sd: "010203"
  nsiList:
    - snssai:
        sst: 1
        sd: "010203"
      nsiInformationList:
        - nrfId: http://172.22.0.12:8000/nnrf-nfm/v1/nf-instances
          nsiId: 22
  amfSetList: []
  amfList: []
  taList:
    - tai:
        plmnId:
          mcc: "001"
          mnc: "01"
        tac: "000001"
      accessType: 3GPP_ACCESS
      supportedSnssaiList:
        - sst: 1
          sd: "010203"

logger:
  enable: true
  level: info
  reportCaller: false
