info:
  version: 1.0.2
  description: PCF initial local configuration

configuration:
  pcfName: PCF
  sbi:
    scheme: http
    registerIPv4: 172.22.0.27
    bindingIPv4: 0.0.0.0
    port: 8000
  serviceNameList:
    - npcf-am-policy-control
    - npcf-smpolicycontrol
    - npcf-bdtpolicycontrol
    - npcf-policyauthorization
    - npcf-eventexposure
    - npcf-ue-policy-control
  nrfUri: http://172.22.0.12:8000
  defaultBdtRefId: BdtPolicyId-
  mongoDBName: free5gc
  mongoDBUrl: mongodb://172.22.0.2:27017
  locality: area1

logger:
  enable: true
  level: info
  reportCaller: false
