version: "3.8"

services:

  oai-gnb:
    build:
      context: .
      dockerfile: build/oai-gnb/Dockerfile
    container_name: oai-gnb
    hostname: oai-gnb
    privileged: true
    volumes:
      - ./config/oai-gnb/gnb.conf:/opt/oai-gnb/etc/gnb.conf:ro
    networks:
      isac_net:
        ipv4_address: 172.22.0.23
    restart: unless-stopped

networks:
  isac_net:
    external: true
