version: "3.8"

x-open5gs: &open5gs-base
  build:
    context: .
    dockerfile: Dockerfile.open5gs
  restart: unless-stopped
  networks:
    - isac_net

services:

  mongo:
    image: mongo:6.0
    container_name: mongo
    hostname: mongo
    volumes:
      - mongodbdata:/data/db
    networks:
      isac_net:
        ipv4_address: 172.22.0.2
    restart: unless-stopped

  webui:
    <<: *open5gs-base
    container_name: webui
    hostname: webui
    environment:
      - COMPONENT_NAME=webui
      - DB_URI=mongodb://172.22.0.2/open5gs
    ports:
      - "${WEBUI_PORT:-9999}:9999"
    networks:
      isac_net:
        ipv4_address: 172.22.0.26
    depends_on:
      - mongo

  nrf:
    <<: *open5gs-base
    container_name: nrf
    hostname: nrf
    environment:
      - COMPONENT_NAME=nrf
    volumes:
      - ./config/open5gs/nrf.yaml:/etc/open5gs/nrf.yaml:ro
      - ./log:/var/log/open5gs
    networks:
      isac_net:
        ipv4_address: 172.22.0.12

  scp:
    <<: *open5gs-base
    container_name: scp
    hostname: scp
    environment:
      - COMPONENT_NAME=scp
    volumes:
      - ./config/open5gs/scp.yaml:/etc/open5gs/scp.yaml:ro
      - ./log:/var/log/open5gs
    networks:
      isac_net:
        ipv4_address: 172.22.0.35
    depends_on:
      - nrf

  ausf:
    <<: *open5gs-base
    container_name: ausf
    hostname: ausf
    environment:
      - COMPONENT_NAME=ausf
    volumes:
      - ./config/open5gs/ausf.yaml:/etc/open5gs/ausf.yaml:ro
      - ./log:/var/log/open5gs
    networks:
      isac_net:
        ipv4_address: 172.22.0.11
    depends_on:
      - scp

  udr:
    <<: *open5gs-base
    container_name: udr
    hostname: udr
    environment:
      - COMPONENT_NAME=udr
    volumes:
      - ./config/open5gs/udr.yaml:/etc/open5gs/udr.yaml:ro
      - ./log:/var/log/open5gs
    networks:
      isac_net:
        ipv4_address: 172.22.0.14
    depends_on:
      - mongo
      - scp

  udm:
    <<: *open5gs-base
    container_name: udm
    hostname: udm
    environment:
      - COMPONENT_NAME=udm
    volumes:
      - ./config/open5gs/udm.yaml:/etc/open5gs/udm.yaml:ro
      - ./log:/var/log/open5gs
    networks:
      isac_net:
        ipv4_address: 172.22.0.13
    depends_on:
      - scp

  pcf:
    <<: *open5gs-base
    container_name: pcf
    hostname: pcf
    environment:
      - COMPONENT_NAME=pcf
    volumes:
      - ./config/open5gs/pcf.yaml:/etc/open5gs/pcf.yaml:ro
      - ./log:/var/log/open5gs
    networks:
      isac_net:
        ipv4_address: 172.22.0.27
    depends_on:
      - mongo
      - scp

  bsf:
    <<: *open5gs-base
    container_name: bsf
    hostname: bsf
    environment:
      - COMPONENT_NAME=bsf
    volumes:
      - ./config/open5gs/bsf.yaml:/etc/open5gs/bsf.yaml:ro
      - ./log:/var/log/open5gs
    networks:
      isac_net:
        ipv4_address: 172.22.0.29
    depends_on:
      - mongo
      - scp

  nssf:
    <<: *open5gs-base
    container_name: nssf
    hostname: nssf
    environment:
      - COMPONENT_NAME=nssf
    volumes:
      - ./config/open5gs/nssf.yaml:/etc/open5gs/nssf.yaml:ro
      - ./log:/var/log/open5gs
    networks:
      isac_net:
        ipv4_address: 172.22.0.28
    depends_on:
      - scp

  amf:
    <<: *open5gs-base
    container_name: amf
    hostname: amf
    environment:
      - COMPONENT_NAME=amf
    volumes:
      - ./config/open5gs/amf.yaml:/etc/open5gs/amf.yaml:ro
      - ./log:/var/log/open5gs
    networks:
      isac_net:
        ipv4_address: 172.22.0.10
    depends_on:
      - scp

  smf:
    <<: *open5gs-base
    container_name: smf
    hostname: smf
    environment:
      - COMPONENT_NAME=smf
    volumes:
      - ./config/open5gs/smf.yaml:/etc/open5gs/smf.yaml:ro
      - ./log:/var/log/open5gs
    networks:
      isac_net:
        ipv4_address: 172.22.0.7
    depends_on:
      - scp

  upf:
    <<: *open5gs-base
    container_name: upf
    hostname: upf
    environment:
      - COMPONENT_NAME=upf
    volumes:
      - ./config/open5gs/upf.yaml:/etc/open5gs/upf.yaml:ro
      - ./log:/var/log/open5gs
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    networks:
      isac_net:
        ipv4_address: 172.22.0.8
    depends_on:
      - smf

volumes:
  mongodbdata:

networks:
  isac_net:
    name: isac_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
