logger:
  file:
    path: /var/log/open5gs/bsf.log
  level: info

bsf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
    client:
      scp:
        - uri: http://172.22.0.35:7777
  db_uri: mongodb://172.22.0.2/open5gs
