logger:
  file:
    path: /var/log/open5gs/pcf.log
  level: info

pcf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
    client:
      scp:
        - uri: http://172.22.0.35:7777
  metrics:
    server:
      - address: 0.0.0.0
        port: 9090
  db_uri: mongodb://172.22.0.2/open5gs
