logger:
  file:
    path: /var/log/open5gs/smf.log
  level: info

smf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
    client:
      scp:
        - uri: http://172.22.0.35:7777
  pfcp:
    server:
      - address: 0.0.0.0
    client:
      upf:
        - address: 172.22.0.8
  gtpc:
    server:
      - address: 0.0.0.0
  gtpu:
    server:
      - address: 0.0.0.0
  metrics:
    server:
      - address: 0.0.0.0
        port: 9090
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet
  dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1400
